### ISSUE TITLE
cannot import name 'make_bbox_loader' from 'maskrcnn_benchmark.data.build'

### ISSUE THREAD

**Issue by Xuxiaoxiaohaha** [YuyangSunshine/ABR_IOD#6]
When i am trying to run 'bash scripts/run_firststep.sh',it gives "cannot import name 'make_bbox_loader' from 'maskrcnn_benchmark.data.build'" error!
Could you help me?

>Traceback (most recent call last):
  File "tools/prototype_box_selection.py", line 23, in <module>
    from maskrcnn_benchmark.data.build import make_bbox_loader # import data set
ImportError: cannot import name 'make_bbox_loader' from 'maskrcnn_benchmark.data.build' (/home/xqx/ABR_IOD-main/maskrcnn-benchmark/maskrcnn_benchmark/data/build.py)

**Comment by xiyouji6** [comment]
> When i am trying to run 'bash scripts/run_firststep.sh',it gives "cannot import name 'make_bbox_loader' from 'maskrcnn_benchmark.data.build'" error! Could you help me?
> 
> > Traceback (most recent call last):
> > File "tools/prototype_box_selection.py", line 23, in 
> > from maskrcnn_benchmark.data.build import make_bbox_loader # import data set
> > ImportError: cannot import name 'make_bbox_loader' from 'maskrcnn_benchmark.data.build' (/home/xqx/ABR_IOD-main/maskrcnn-benchmark/maskrcnn_benchmark/data/build.py)
hello，好巧，请问您当时跑这个代码时在连续进行多个任务的增量检测时是否跑通了呢

**Comment by Xuxiaoxiaohaha** [comment]
> > When i am trying to run 'bash scripts/run_firststep.sh',it gives "cannot import name 'make_bbox_loader' from 'maskrcnn_benchmark.data.build'" error! Could you help me?
> > > Traceback (most recent call last):
> > > File "tools/prototype_box_selection.py", line 23, in
> > > from maskrcnn_benchmark.data.build import make_bbox_loader # import data set
> > > ImportError: cannot import name 'make_bbox_loader' from 'maskrcnn_benchmark.data.build' (/home/xqx/ABR_IOD-main/maskrcnn-benchmark/maskrcnn_benchmark/data/build.py)
> > > hello，好巧，请问您当时跑这个代码时在连续进行多个任务的增量检测时是否跑通了呢

跑通了，不过环境是当时配好了，现在有点点忘了...如果你需要帮助，可以邮箱联系我xuqixing@stu.hit.edu.cn

**Comment by xiyouji6** [comment]
> > > When i am trying to run 'bash scripts/run_firststep.sh',it gives "cannot import name 'make_bbox_loader' from 'maskrcnn_benchmark.data.build'" error! Could you help me?
> > > > Traceback (most recent call last):
> > > > File "tools/prototype_box_selection.py", line 23, in
> > > > from maskrcnn_benchmark.data.build import make_bbox_loader # import data set
> > > > ImportError: cannot import name 'make_bbox_loader' from 'maskrcnn_benchmark.data.build' (/home/xqx/ABR_IOD-main/maskrcnn-benchmark/maskrcnn_benchmark/data/build.py)
> > > > hello，好巧，请问您当时跑这个代码时在连续进行多个任务的增量检测时是否跑通了呢
> 
> 跑通了，不过环境是当时配好了，现在有点点忘了...如果你需要帮助，可以邮箱联系我[xuqixing@stu.hit.edu.cn](mailto:xuqixing@stu.hit.edu.cn)

好嘞，非常感谢
